Update public facing id of project to be the id of the submission
OpenTechFund/opentech.fund pull request #3944
Opened 2024-05-28 05:32 UTC by theskumar

Update the project urls to use it's submission id instead of the project's db id

The reason for the update is that there are two main entities in the system, one submission and other project.
The ids of the submission is linkable in the communiction and also used for referencing at different places. 

Considering a project is an extension of application submission, if we have the project publically available id same as that of it's submission it always to link and reference the project by the same id. 

## Test Steps

 - [ ] General regression test and make sure all the urls in the project section resolve and link to the right pages

2024-11-13 09:47 UTC, frjo requested changes
This needs a rebase. Would be good to get this in, it's the right approach I think.

2025-02-05 07:17 UTC, theskumar commented
I think this needs to done fresh now, given the number of merge conflicts and new code that might have got added after.

2025-02-05 07:20 UTC, frjo approved these changes

2025-02-14 07:52 UTC, theskumar commented on hypha/apply/projects/templates/application_projects/includes/invoice_block.html
> -</ul>
Removed this unused template.

2025-02-14 07:52 UTC, theskumar commented on hypha/apply/projects/templates/application_projects/modals/approve_contract.html
> +    {% url 'apply:projects:contract_approve' pk=object.submission.id as url %}
Minor copy and style update.

2025-02-14 07:53 UTC, theskumar commented on hypha/apply/projects/templates/application_projects/modals/submit_contracting_documents.html
> +    {% url 'apply:projects:contract_doc_upload' pk=object.submission.id as url %}
Minor style update of the modal text.

2025-02-14 08:45 UTC, theskumar commented on hypha/apply/projects/permissions.py
> +        return True, "Vendor can view all documents"
superuser and the applicant itself were not able to view the contracting documents uploaded. I've updated the code to fix it, please advise. @frjo @sandeepsajan0 @wes-otf

2025-02-14 08:46 UTC, theskumar commented on hypha/apply/projects/permissions.py
> +        return True, "Vendor can view all documents"
To reproduce, after uploading the additional documents in the contract, login as the applicant and try clicking on the "view" button. 
![Screenshot 2025-02-14 at 8  46 13@2x](https://github.com/user-attachments/assets/89243105-9cb0-4695-8083-5069829019e9)

2025-02-14 08:52 UTC, frjo commented on hypha/apply/projects/permissions.py
> +        return True, "Vendor can view all documents"
@theskumar This is a bug so your fix is correct. Applicant are the ones uploading these documents so they should be able to view them.

My guess this bug was introduced when we added the feature to limit what internal groups cound access these documents (staff, finance etc.).

2025-02-14 11:16 UTC, theskumar commented on hypha/apply/projects/permissions.py
> +        return True, "Vendor can view all documents"
ok

2025-02-14 11:18 UTC, theskumar commented
This became a bit bigger PR than I expected. Almost all of the public facing urls should be in the form of `/apply/projects/<submission-id>/...` now. 

There are minor style update to models and a bug fix for contracting document visibility. 

@frjo @wes-otf best way to test this out is to browse through the project section and try out all the flow.

2025-02-20 08:46 UTC, frjo commented
The edit invoice url still uses the project id.

Some test seems to need to be updated as well.

2025-02-20 08:47 UTC, theskumar commented
> The edit invoice url still uses the project id.

ok. let me check.

2025-02-20 08:51 UTC, frjo commented
The "View comment" link on invoice detail view in the status block also still use the project id.

2025-02-20 16:53 UTC, frjo commented
Now edit and view comment links works for invoices. Just some tests to fix and we can put this on test.

2025-02-21 10:27 UTC, frjo approved these changes

2025-02-21 13:58 UTC, theskumar commented
Testcases updated.

2025-02-28 14:26 UTC, frjo commented
@theskumar Merging in my modal fixes created some merge conflicts here.

2025-03-01 15:32 UTC, theskumar commented
No worries. On it.

2025-03-09 09:41 UTC, frjo commented
@theskumar This needs a new rebase after your other PR that I have merged in.

After the rebase I plan to merge these three PR:s as well. Have tested them on test and they seem to work without issues.

2025-03-10 12:30 UTC, theskumar commented
Ready for final review and merge. 

I've merged in project header pr #4413 .

2025-03-11 13:59 UTC, merged